kind: Pod
apiVersion: v1
metadata:
  name: annotations
  labels:
    course: k8
    trainer: hemanth
  annotations:
    kubernetes.io/created-by: 'hemanth'
    jenkins.build.url: 'https://jenkins.hemanth78s.online/expense/job/backend/54'
spec:
  containers:
  - name: nginx
    image: nginx