kind: Pod
apiVersion: v1
metadata:
  name: resourcess
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
    # soft limit
    requests:
      cpu: "100m"
      memory: "128mi"
    # limits should be atleast or more than requests i.e hard limit
    limits:
      cpu: "100m"
      memory: "128mi"